# Generated by Django 5.1.3 on 2025-02-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_recipients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_intake_ml', models.IntegerField()),
                ('physical_activity_steps', models.IntegerField(blank=True, null=True)),
                ('sleep_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50)),
                ('specific_meal', models.CharField(blank=True, max_length=255, null=True)),
                ('medication_taken', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stress_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('hours_since_last_visit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_of_last_visit_seconds', models.IntegerField(blank=True, null=True)),
                ('bladder_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_rate_variability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_next_visit_time', models.DateTimeField(blank=True, null=True)),
                ('care_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data', to='core.carerecipient')),
            ],
        ),
    ]
