# Generated by Django 5.1.3 on 2024-11-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdata',
            name='predicted_next_visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
