# Generated by Django 5.1.3 on 2025-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdata',
            name='medication_taken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
